import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        {children}
        {/* <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>  */}
      </body>
    </html>
  )
}
